services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn insurance_hakaton.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/c/Users/Makarov/PycharmProjects/insurance_hakaton/static

    ports:
      - "8001:8000"
    env_file:
      - ./.env

    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/c/Program Files/PostgreSQL/16/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=insurance
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/c/Users/Makarov/PycharmProjects/insurance_hakaton/static
    ports:
      - "81:80"
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
