# Generated by Django 5.0.2 on 2024-02-15 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_industry', '0001_initial'),
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limitName', models.CharField(max_length=150)),
                ('limitSumm', models.PositiveIntegerField(default=0)),
                ('verboseIndustry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_industry.industry')),
                ('verboseTariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.tariff')),
            ],
        ),
    ]
